version: "3.9"

services:
  db:
    image: postgres:13.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db-variables.prod.env
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "gunicorn NoteApplication.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web


volumes:
  postgres_data:





