version: "3.9"

services:
  db:
    image: postgres:13.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db-variables.env
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  jenkins:
    build: .
    user: root
    volumes:
      - /jenkins/data:/var/jenkins_home
      - /jenkins/artifacts:/var/jenkins_artifacts
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nginx:
      image: nginx:1.17
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - jenkins_net

volumes:
  postgres_data:



